apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: helloworld-gateway
  namespace: default
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 5000
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: helloworld-http-route
  namespace: default
spec:
  parentRefs:
  - name: helloworld-gateway
  - group: ""
    kind: Service
    name: helloworld
    port: 5000
  rules:
  - matches:
    - path:
        type: Exact
        value: /hello
    backendRefs:
    - name: helloworld-stable
      kind: Service
      port: 5000
    - name: helloworld-canary
      kind: Service
      port: 5000
